<?php
/**
 * ConfirmSdkOrderPayloadTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  RPay\POK\PaymentsSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * RPay API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RPay\POK\PaymentsSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ConfirmSdkOrderPayloadTest Class Doc Comment
 *
 * @category    Class
 * @description ConfirmSdkOrderPayload
 * @package     RPay\POK\PaymentsSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConfirmSdkOrderPayloadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ConfirmSdkOrderPayload"
     */
    public function testConfirmSdkOrderPayload()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paymentMethod"
     */
    public function testPropertyPaymentMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paymentMethodId"
     */
    public function testPropertyPaymentMethodId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "billingInfoId"
     */
    public function testPropertyBillingInfoId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
