<?php
/**
 * SdkOrdersApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  RPay\POK\PaymentsSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * RPay API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RPay\POK\PaymentsSdk\Test\Api;

use \RPay\POK\PaymentsSdk\Configuration;
use \RPay\POK\PaymentsSdk\ApiException;
use \RPay\POK\PaymentsSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SdkOrdersApiTest Class Doc Comment
 *
 * @category Class
 * @package  RPay\POK\PaymentsSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SdkOrdersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for confirmOrder
     *
     * Confirm order..
     *
     */
    public function testConfirmOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for confirmOrderAsGuest
     *
     * Confirm order with guest checkout.
     *
     */
    public function testConfirmOrderAsGuest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSdkOrderById
     *
     * Retrieve an order.
     *
     */
    public function testGetSdkOrderById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
